Repository taikoxyz/taiko-client, pull requests merged in 2024-01, with the labels that each got.

#490 fix(prover): fix `--prover.allowance` flag
  prover/prover.go
  prover/prover_test.go
Labels: area.client, area.client.prover

#491 feat(prover): add more comments to prover package
  prover/db/db.go
  prover/guardian_prover_sender/guardian_prover.go
  prover/prover.go
  prover/prover_test.go
Labels: area.client, area.client.prover

#492 feat(prover): set default `--prover.proveUnassignedBlocks` and `--mode.contester` value for guardian provers
  prover/config.go
  prover/config_test.go
Labels: area.client.prover

#495 feat(client): upgrade shell scripts and replace docker image links
  integration_test/entrypoint.sh
  integration_test/nodes/docker-compose.yml
  integration_test/nodes/init.sh
  scripts/common.sh
Labels: type.enhancement, area.client

#497 feat(prover): check guardian prover contract address
  prover/prover.go
Labels: area.client.prover

#496 feat(prover): fix / upgrade integration test
  .github/workflows/test.yml
  Makefile
  bindings/encoding/input_test.go
  docker/docker_env.sh
  docker/nodes/docker-compose.yml
  docker/nodes/jwt.hex
  docker/start.sh
  docker/stop.sh
  driver/chain_syncer/calldata/syncer_test.go
  driver/chain_syncer/chain_syncer_test.go
  driver/driver_test.go
  integration_test/deploy_l1_contract.sh
  integration_test/entrypoint.sh
  integration_test/l1_env.sh
  integration_test/nodes/init.sh
  integration_test/test_env.sh
  integration_test/util/wait_for_node.sh
  pkg/rpc/utils_test.go
  proposer/proposer_test.go
  proposer/prover_selector/eth_fee_eoa_selector_test.go
  prover/config.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover_test.go
  prover/server/server_test.go
  scripts/common.sh
  testutils/suite.go
Labels: type.enhancement, area.client, type.test

#498 feat(prover): add readme for guiding how to debug
  integration_test/README.md
  integration_test/test_env.sh
Labels: area.docs, area.client

#502 feat(proposer): changes based on protocol `AssignmentHook` updates
  .github/workflows/test.yml
  bindings/.githead
  bindings/encoding/input.go
  bindings/encoding/input_test.go
  bindings/gen_assignment_hook.go
  proposer/prover_selector/eth_fee_eoa_selector.go
  prover/prover.go
  prover/server/api.go
  prover/server/server.go
  prover/server/server_test.go
  testutils/helper.go
Labels: area.client, area.client.proposer

#501 feat(rpc): fix a bug and update logic
  common/utils/utils.go
  driver/driver.go
  go.mod
  go.sum
  pkg/rpc/methods.go
  pkg/rpc/utils.go
Labels: type.bug, type.enhancement

#500 chore(style): update `golangci` lint
  .golangci.yml
  bindings/encoding/custom_error.go
  bindings/encoding/custom_error_test.go
  bindings/encoding/struct.go
  bindings/encoding/struct_test.go
  cmd/flags/common.go
  cmd/flags/driver.go
  cmd/flags/proposer.go
  cmd/flags/prover.go
  cmd/logger/logger.go
  cmd/main.go
  common/utils/utils.go
  docs/docs.go
  driver/anchor_tx_constructor/anchor_tx_constructor.go
  driver/anchor_tx_constructor/anchor_tx_constructor_test.go
  driver/chain_syncer/beaconsync/progress_tracker.go
  driver/chain_syncer/beaconsync/progress_tracker_test.go
  driver/chain_syncer/calldata/syncer.go
  driver/chain_syncer/calldata/syncer_test.go
  driver/chain_syncer/chain_syncer.go
  driver/chain_syncer/chain_syncer_test.go
  driver/config.go
  driver/config_test.go
  driver/driver.go
  driver/driver_test.go
  driver/state/state_test.go
  metrics/metrics.go
  pkg/chain_iterator/block_batch_iterator.go
  pkg/chain_iterator/block_batch_iterator_test.go
  pkg/rpc/dial.go
  pkg/rpc/fallback.go
  pkg/rpc/methods.go
  pkg/rpc/methods_test.go
  pkg/txlistvalidator/tx_list_validator.go
  pkg/txlistvalidator/tx_list_validator_test.go
  proposer/config.go
  proposer/config_test.go
  proposer/proposer.go
  proposer/proposer_test.go
  proposer/prover_selector/eth_fee_eoa_selector.go
  proposer/prover_selector/eth_fee_eoa_selector_test.go
  prover/anchor_tx_validator/anchor_tx_validator.go
  prover/anchor_tx_validator/anchor_tx_validator_test.go
  prover/config.go
  prover/db/db.go
  prover/guardian_prover_sender/guardian_prover.go
  prover/proof_producer/sgx_producer.go
  prover/proof_producer/zkevm_rpcd_producer.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/builder_test.go
  prover/proof_submitter/transaction/sender.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
  prover/prover_test.go
  prover/server/server.go
  prover/server/server_test.go
  testutils/helper.go
  testutils/suite.go
  version/version.go
Labels: type.enhancement

#504 feat(pkg): fix a log issue in `ensureGenesisMatched` && update a config
  pkg/rpc/methods.go
Labels: type.enhancement, area.client

#510 feat(rpc): improve reorg checks
  driver/anchor_tx_constructor/anchor_tx_constructor.go
  driver/chain_syncer/calldata/syncer.go
  driver/driver_test.go
  pkg/rpc/methods.go
  pkg/rpc/methods_test.go
  pkg/rpc/utils.go
  prover/prover.go
Labels: type.enhancement, area.client, area.client.prover, area.client.driver

#511 fix(rpc): fix an issue in `checkSyncedL1SnippetFromAnchor` && add more logs
  pkg/rpc/methods.go
Labels: area.client

#509 feat(pkg): delete reverse iter
  pkg/chain_iterator/block_batch_iterator.go
  pkg/chain_iterator/block_batch_iterator_test.go
  pkg/chain_iterator/event_iterator/block_proposed_iterator.go
  pkg/chain_iterator/event_iterator/transition_proven_iterator.go
Labels: type.enhancement, area.client

#519 feat(bindings): update `AssigmentHook` signing based on protocol updates
  bindings/encoding/input.go
  bindings/encoding/struct.go
Labels: area.client

#507 feat(config): simplify config loading
  cmd/flags/common.go
  driver/chain_syncer/calldata/syncer_test.go
  driver/chain_syncer/chain_syncer_test.go
  driver/config.go
  driver/config_test.go
  driver/driver.go
  driver/driver_test.go
  pkg/rpc/client.go
  pkg/rpc/client_test.go
  pkg/rpc/dial.go
  pkg/rpc/dial_test.go
  pkg/rpc/ethclient.go
  proposer/config.go
  proposer/config_test.go
  proposer/proposer.go
  proposer/proposer_test.go
  prover/config.go
  prover/config_test.go
  prover/proof_submitter/proof_submitter_test.go
  prover/prover.go
  prover/prover_test.go
  prover/server/server_test.go
Labels: area.client

#513 feat(prover): move sub event logic into event function.
  internal/docker/nodes/.env
  prover/prover.go
  prover/prover_test.go
Labels: type.enhancement, area.client.proposer

#516 feat(prover): delete result channel in proof_producer
  prover/proof_producer/dummy_producer.go
  prover/proof_producer/dummy_producer_test.go
  prover/proof_producer/guardian_producer.go
  prover/proof_producer/guardian_producer_test.go
  prover/proof_producer/optimistic_producer.go
  prover/proof_producer/optimistic_producer_test.go
  prover/proof_producer/proof_producer.go
  prover/proof_producer/sgx_and_zkevm_rpcd_producer.go
  prover/proof_producer/sgx_producer.go
  prover/proof_producer/sgx_producer_test.go
  prover/proof_producer/zkevm_rpcd_producer.go
  prover/proof_producer/zkevm_rpcd_producer_test.go
  prover/proof_submitter/proof_submitter.go
Labels: type.enhancement, area.client.proposer

#532 feat(prover): update unretryable error check
  prover/proof_submitter/transaction/sender.go
Labels: area.client.prover

#539 chore(workflow): fix workflow errors
  bindings/.githead
  internal/docker/nodes/docker-compose.yml
Labels: area.client

#541 chore(ci): update integration test scripts based on the latest protocol updates
  bindings/.githead
  bindings/encoding/struct.go
  bindings/encoding/struct_test.go
  bindings/gen_address_manager.go
  bindings/gen_guardian_prover.go
  bindings/gen_lib_proving.go
  bindings/gen_taiko_l1.go
  bindings/gen_taiko_l2.go
  driver/anchor_tx_constructor/anchor_tx_constructor.go
  integration_test/deploy_l1_contract.sh
  pkg/rpc/methods_test.go
  proposer/config_test.go
  prover/anchor_tx_validator/anchor_tx_validator_test.go
  scripts/gen_bindings.sh
Labels: area.client
