Repository taikoxyz/taiko-client, pull requests merged in 2024-03, with the labels that each got.

#607 feat(bindings): update bindings
  bindings/.githead
  bindings/encoding/input.go
  bindings/gen_assignment_hook.go
  bindings/gen_guardian_prover.go
  bindings/gen_lib_proposing.go
  bindings/gen_taiko_l1.go
Labels: area.client

#606 feat(sender): fix bug in sender
  driver/driver_test.go
  internal/sender/common.go
  internal/sender/sender.go
  internal/sender/sender_test.go
  internal/testutils/helper.go
  proposer/proposer.go
  proposer/proposer_test.go
Labels: type.bug, area.client

#591 feat(state): upgrade state
  driver/state/state.go
  pkg/rpc/subscription.go
  pkg/rpc/subscription_test.go
Labels: type.bug, type.enhancement, area.client.driver

#589 feat(client): simplify config
  cmd/flags/proposer.go
  driver/chain_syncer/calldata/syncer_test.go
  driver/chain_syncer/chain_syncer_test.go
  driver/config.go
  driver/driver.go
  driver/driver_test.go
  internal/testutils/suite.go
  pkg/chain_iterator/block_batch_iterator.go
  pkg/chain_iterator/block_batch_iterator_test.go
  pkg/rpc/client.go
  pkg/rpc/client_test.go
  proposer/config.go
  proposer/proposer.go
  proposer/proposer_test.go
  prover/proof_submitter/proof_submitter_test.go
  prover/prover.go
  prover/prover_test.go
  prover/server/server_test.go
Labels: area.client

#609 feat(tx_list_validator): remove unused code in `tx_list_validator` package
  driver/chain_syncer/calldata/syncer.go
  pkg/txlist_validator/tx_list_validator.go
  pkg/txlist_validator/tx_list_validator_test.go
Labels: type.enhancement, area.client, area.client.driver

#611 feat(pkg): remove `defaultMaxTransactionsPerBlock` config
  driver/chain_syncer/calldata/syncer.go
  pkg/rpc/methods.go
  pkg/rpc/methods_test.go
  pkg/txlist_validator/tx_list_validator.go
  pkg/txlist_validator/tx_list_validator_test.go
  proposer/proposer.go
  proposer/proposer_test.go
Labels: area.client, area.client.proposer

#586 refactor(prover): refactor prover / guardian prover
  .gitignore
  bindings/encoding/input.go
  bindings/gen_guardian_verifier.go
  bindings/gen_sgx_verifier.go
  cmd/flags/prover.go
  driver/chain_syncer/calldata/syncer.go
  driver/driver_test.go
  internal/sender/sender.go
  internal/testutils/helper.go
  internal/testutils/suite.go
  pkg/rpc/methods.go
  pkg/rpc/methods_test.go
  pkg/rpc/tx_blob.go
  pkg/rpc/tx_blob_test.go
  pkg/rpc/utils.go
  proposer/proposer.go
  prover/config.go
  prover/config_test.go
  prover/event_handler/assignment_expired.go
  prover/event_handler/block_proposed.go
  prover/event_handler/block_verified.go
  prover/event_handler/interface.go
  prover/event_handler/transition_contested.go
  prover/event_handler/transition_proved.go
  prover/event_handler/util.go
  prover/event_handler/util_test.go
  prover/guardian.go
  prover/guardian_prover_heartbeater/guardian_prover.go
  prover/guardian_prover_heartbeater/interface.go
  prover/init.go
  prover/init_test.go
  prover/proof_submitter/interface.go
  prover/proof_submitter/proof_contester.go
  prover/proof_submitter/proof_submitter.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/builder.go
  prover/proof_submitter/transaction/builder_test.go
  prover/proof_submitter/transaction/sender.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
  prover/prover_test.go
  prover/server/api.go
  prover/server/server.go
  prover/server/server_test.go
  prover/shared_state/state.go
  prover/shared_state/state_test.go
  scripts/gen_bindings.sh
Labels: type.enhancement, area.client, area.client.prover

#616 feat(prover): improve prover implementation
  prover/guardian.go
  prover/init.go
  prover/init_test.go
  prover/proof_submitter/proof_contester.go
  prover/proof_submitter/proof_submitter.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/sender.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
  prover/prover_test.go
Labels: type.enhancement, area.client

#617 feat(metrics): update default metrics registry
  internal/metrics/metrics.go
Labels: area.client

#612 feat(proposer): introduce proposer transaction builder
  cmd/flags/prover.go
  internal/sender/sender.go
  internal/testutils/helper.go
  pkg/rpc/tx_blob.go
  pkg/rpc/tx_blob_test.go
  proposer/proposer.go
  proposer/proposer_test.go
  proposer/transaction_builder/blob.go
  proposer/transaction_builder/calldata.go
  proposer/transaction_builder/calldata_test.go
  proposer/transaction_builder/common.go
  proposer/transaction_builder/common_test.go
  proposer/transaction_builder/interface.go
  prover/config.go
  prover/server/api.go
  prover/server/server.go
Labels: type.enhancement, area.client, area.client.proposer

#619 feat(bindings): update Go contract bindings
  bindings/.githead
  bindings/gen_assignment_hook.go
  bindings/gen_guardian_prover.go
  bindings/gen_taiko_timelock_controller.go
  bindings/gen_taiko_token.go
Labels: area.client

#618 feat(prover): update server APIs
  internal/testutils/helper.go
  prover/event_handler/assignment_expired.go
  prover/event_handler/block_proposed.go
  prover/event_handler/transition_contested.go
  prover/event_handler/transition_proved.go
  prover/proof_producer/proof_producer.go
  prover/proof_submitter/interface.go
  prover/prover.go
  prover/server/api.go
  prover/server/server.go
  prover/server/server_test.go
Labels: area.client, area.client.prover

#621 feat(prover): cleanup more database related code
  prover/db/db.go
  prover/db/db_test.go
  prover/guardian_prover_heartbeater/guardian_prover.go
  prover/guardian_prover_heartbeater/interface.go
  prover/prover.go
Labels: area.client, area.client.prover

#622 feat(ci): update golangci to v1.56.2 and fix ci
  Makefile
  driver/driver.go
  driver/txlist_fetcher/blob.go
  driver/txlist_fetcher/calldata.go
  pkg/chain_iterator/block_batch_iterator_test.go
  pkg/rpc/methods.go
  pkg/rpc/methods_test.go
  pkg/rpc/subscription_test.go
  proposer/proposer.go
  proposer/prover_selector/eth_fee_eoa_selector.go
  prover/anchor_tx_validator/anchor_tx_validator.go
  prover/anchor_tx_validator/anchor_tx_validator_test.go
  prover/event_handler/util.go
  prover/init.go
  prover/proof_producer/dummy_producer.go
  prover/proof_producer/dummy_producer_test.go
  prover/proof_producer/guardian_producer.go
  prover/proof_producer/optimistic_producer.go
  prover/proof_producer/optimistic_producer_test.go
  prover/proof_producer/proof_producer.go
  prover/proof_producer/sgx_producer.go
  prover/proof_submitter/proof_contester.go
  prover/proof_submitter/proof_submitter.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/builder.go
  prover/proof_submitter/transaction/sender.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
Labels: area.client

#624 feat(prover): parse contest submission custom errors
  bindings/encoding/custom_error.go
  prover/proof_submitter/proof_contester.go
  prover/proof_submitter/proof_submitter.go
Labels: type.enhancement, area.client

#623 feat(prover): remove more database related code
  cmd/flags/prover.go
  prover/config.go
  prover/config_test.go
  prover/prover_test.go
Labels: area.client

#625 feat(sender): upgrade sender txID
  internal/sender/sender.go
Labels: area.client, area.client.proposer

#626 feat(sender): update sender
  driver/txlist_fetcher/blob.go
  internal/testutils/interfaces.go
  pkg/rpc/beaconclient.go
  pkg/rpc/client.go
  pkg/rpc/methods.go
  pkg/rpc/tx_blob.go
  pkg/sender/common.go
  pkg/sender/sender.go
  pkg/sender/sender_test.go
  proposer/proposer.go
  proposer/proposer_test.go
  proposer/transaction_builder/common_test.go
  prover/init.go
  prover/proof_submitter/proof_contester.go
  prover/proof_submitter/proof_submitter.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/sender.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
Labels: type.enhancement, area.client

#628 feat(sender): improve default values setting
  go.mod
  go.sum
  pkg/sender/common.go
  pkg/sender/common_test.go
  pkg/sender/sender.go
Labels: type.enhancement, area.client

#629 fix(driver): fix a blob decoding issue
  driver/chain_syncer/calldata/syncer.go
  pkg/rpc/tx_blob.go
Labels: type.bug, area.client, area.client.driver

#620 refactor(pkg): refactor logic of block_batch_iterator
  cmd/flags/prover.go
  pkg/chain_iterator/block_batch_iterator.go
  pkg/chain_iterator/block_batch_iterator_test.go
  pkg/chain_iterator/event_iterator/block_proposed_iterator.go
  pkg/chain_iterator/event_iterator/transition_proven_iterator.go
  prover/config.go
  prover/prover.go
Labels: type.enhancement, area.client

#630 feat(metrics): add more transaction sender metrics
  internal/metrics/metrics.go
  pkg/sender/sender.go
Labels: type.enhancement, area.client

#632 feat(bindings): update Go contract bindings && add more logs for prover
  bindings/.githead
  bindings/gen_taiko_token.go
  prover/proof_submitter/proof_submitter.go
  prover/prover.go
Labels: area.client

#633 feat(prover): improve prover
  pkg/sender/sender.go
  prover/event_handler/block_proposed.go
  prover/event_handler/interface.go
  prover/guardian.go
  prover/init.go
  prover/proof_producer/dummy_producer.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/builder.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
  prover/shared_state/state.go
  prover/shared_state/state_test.go
Labels: type.enhancement, area.client

#634 fix(driver): fix a reorg check issue in driver
  bindings/.githead
  bindings/gen_sgx_verifier.go
  bindings/gen_taiko_l2.go
  driver/chain_syncer/calldata/syncer.go
  pkg/chain_iterator/block_batch_iterator.go
Labels: area.client, area.client.driver

#635 feat(prover): improve prover implementation
  pkg/sender/sender.go
  pkg/sender/sender_test.go
  proposer/proposer.go
  proposer/proposer_test.go
  proposer/transaction_builder/calldata_test.go
  prover/event_handler/assignment_expired.go
  prover/event_handler/block_proposed.go
  prover/event_handler/transition_contested.go
  prover/init.go
  prover/proof_producer/dummy_producer_test.go
  prover/proof_producer/guardian_producer.go
  prover/proof_producer/optimistic_producer.go
  prover/proof_producer/proof_producer.go
  prover/proof_producer/sgx_producer.go
  prover/proof_producer/sgx_producer_test.go
  prover/proof_submitter/proof_contester.go
  prover/proof_submitter/proof_submitter.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/builder.go
  prover/proof_submitter/transaction/builder_test.go
  prover/proof_submitter/transaction/sender.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
Labels: type.enhancement, area.client, area.client.prover

#636 feat(blob): add min blob fee
  pkg/rpc/tx_blob.go
Labels: area.client

#639 feat(driver): improve driver implementation
  driver/anchor_tx_constructor/anchor_tx_constructor.go
  driver/chain_syncer/beaconsync/progress_tracker.go
  driver/chain_syncer/beaconsync/syncer.go
  driver/chain_syncer/calldata/syncer.go
  driver/chain_syncer/chain_syncer.go
  driver/driver.go
  driver/state/l1_current.go
  driver/state/state.go
  driver/state/state_test.go
  driver/txlist_fetcher/blob.go
  driver/txlist_fetcher/calldata.go
  driver/txlist_fetcher/interface.go
  pkg/rpc/methods.go
  pkg/rpc/methods_test.go
  proposer/transaction_builder/common.go
  prover/event_handler/transition_contested.go
  prover/event_handler/transition_proved.go
  prover/proof_submitter/proof_submitter.go
Labels: area.client, area.client.driver

#640 feat(driver): update `ForkchoiceStateV1` params
  driver/chain_syncer/calldata/syncer.go
Labels: type.enhancement, area.client, area.client.driver

#641 feat(prover): add `--prover.minEthBalance` and `--prover.minTaikoTokenBalance` flags
  cmd/flags/prover.go
  internal/testutils/helper.go
  prover/config.go
  prover/prover.go
  prover/server/api.go
  prover/server/server.go
  prover/server/server_test.go
Labels: type.enhancement, area.client.prover

#642 feat(prover): improve prover server tier fees check
  prover/server/api.go
Labels: area.client, area.client.prover

#644 feat(pkg): introduce `blob.go`
  driver/txlist_fetcher/blob.go
  pkg/rpc/beaconclient.go
  pkg/rpc/blob.go
  pkg/rpc/blob_tx.go
  pkg/rpc/blob_tx_test.go
Labels: area.client, area.client.driver, area.client.proposer

#646 feat(bindings): update Go contract bindings
  .github/workflows/test.yml
  bindings/.githead
  bindings/gen_taiko_l1.go
  bindings/gen_taiko_l2.go
  driver/chain_syncer/calldata/syncer.go
  internal/testutils/helper.go
  pkg/rpc/methods.go
  pkg/rpc/utils_test.go
  proposer/proposer_test.go
Labels: area.client

#650 fix(cmd): fix some context close issues
  driver/driver.go
  pkg/chain_iterator/block_batch_iterator.go
Labels: type.bug, type.enhancement

#649 feat(proposer): introduce `zlib` for transactions list bytes compression
  driver/chain_syncer/calldata/syncer.go
  internal/utils/util_test.go
  internal/utils/utils.go
  proposer/proposer.go
Labels: type.enhancement, area.client, area.client.proposer

#652 feat(pkg): remove `IsArchiveNode` check for L1 endpoint
  pkg/rpc/client.go
  pkg/rpc/utils.go
Labels: area.client

#656 feat(driver): fix bug
  driver/chain_syncer/calldata/syncer.go
Labels: area.client, area.client.driver

#657 feat(bindings): update Go contract bindings
  bindings/.githead
  bindings/gen_lib_proving.go
  bindings/gen_taiko_l1.go
Labels: area.client

#654 refactor(pkg): remove timeout in WaitTillL2ExecutionEngineSynced
  pkg/rpc/methods.go
  pkg/rpc/methods_test.go
Labels: type.enhancement, area.client

#647 feat(pkg): improve/simplify reorg check logic
  cmd/flags/driver.go
  driver/chain_syncer/calldata/syncer.go
  driver/chain_syncer/calldata/syncer_test.go
  driver/chain_syncer/chain_syncer.go
  driver/chain_syncer/chain_syncer_test.go
  driver/config.go
  driver/driver.go
  internal/testutils/helper.go
  pkg/rpc/methods.go
  prover/proof_submitter/proof_submitter_test.go
Labels: type.enhancement, area.client, area.client.driver

#660 feat(bindings): update Go contract bindings
  bindings/.githead
  bindings/gen_taiko_l2.go
  bindings/gen_tier_provider.go
  scripts/gen_bindings.sh
Labels: area.client

#658 feat(repo): introduce `txmgr` package
  bindings/encoding/input.go
  cmd/flags/common.go
  cmd/flags/proposer.go
  cmd/flags/prover.go
  cmd/flags/txmgr.go
  driver/chain_syncer/calldata/syncer_test.go
  driver/chain_syncer/chain_syncer_test.go
  driver/driver_test.go
  driver/txlist_fetcher/blob.go
  go.mod
  go.sum
  internal/docker/nodes/docker-compose.yml
  internal/testutils/helper.go
  internal/testutils/interfaces.go
  pkg/flags/config.go
  pkg/rpc/beaconclient.go
  pkg/rpc/blob.go
  pkg/rpc/blob_tx.go
  pkg/rpc/blob_tx_test.go
  pkg/rpc/ethclient_test.go
  pkg/sender/common.go
  pkg/sender/common_test.go
  pkg/sender/sender.go
  pkg/sender/sender_test.go
  proposer/config.go
  proposer/config_test.go
  proposer/proposer.go
  proposer/proposer_test.go
  proposer/transaction_builder/blob.go
  proposer/transaction_builder/calldata.go
  proposer/transaction_builder/calldata_test.go
  proposer/transaction_builder/common_test.go
  proposer/transaction_builder/interface.go
  prover/config.go
  prover/config_test.go
  prover/init.go
  prover/proof_submitter/proof_contester.go
  prover/proof_submitter/proof_submitter.go
  prover/proof_submitter/proof_submitter_test.go
  prover/proof_submitter/transaction/builder.go
  prover/proof_submitter/transaction/builder_test.go
  prover/proof_submitter/transaction/sender.go
  prover/proof_submitter/transaction/sender_test.go
  prover/prover.go
  prover/prover_test.go
Labels: type.enhancement, area.client, area.client.prover, area.client.proposer

#662 fix(transaction_builder): fix an issue in `BlobTransactionBuilder.Build`
  driver/config_test.go
  driver/txlist_fetcher/blob.go
  pkg/rpc/beaconclient.go
  proposer/transaction_builder/blob.go
Labels: type.bug, area.client, area.client.proposer

#666 feat(driver): introduce `StateVariablesUpdated` event
  bindings/.githead
  bindings/gen_lib_verifying.go
  bindings/gen_taiko_l1.go
  driver/chain_syncer/calldata/syncer.go
  pkg/rpc/methods.go
Labels: area.client

#667 chore(dep): use forked `txmgr`
  go.mod
  go.sum
Labels: area.client

#668 chore(ci): update CI configs
  .github/workflows/test.yml
  bindings/.githead
Labels: area.client

#669 feat(docker): upgrade docker script
  internal/docker/docker_env.sh
Labels: area.client, type.test

#665 fix(pkg&driver): remove redundant alias
  driver/chain_syncer/calldata/syncer.go
  pkg/rpc/methods.go
Labels: area.client
